# Generated by Django 3.0 on 2020-01-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0002_sign_mobileno'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('facultyid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('mobileno', models.IntegerField(blank=True, max_length=10, null=True)),
                ('admissiondate', models.DateField()),
                ('guardian', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
