# Generated by Django 3.0 on 2020-01-02 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0005_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='mobileno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sign',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sign',
            name='mobileno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobileno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='facultyattendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status_hour1', models.CharField(max_length=10)),
                ('status_hour2', models.CharField(max_length=10)),
                ('status_hour3', models.CharField(max_length=10)),
                ('status_hour4', models.CharField(max_length=10)),
                ('facultyid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attapp.faculty')),
            ],
        ),
    ]
