# Generated by Django 3.0 on 2020-01-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0009_auto_20200102_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Gender',
            new_name='gender',
        ),
    ]
