# Generated by Django 3.0 on 2020-01-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0012_auto_20200103_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admissiondate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
