# Generated by Django 3.0 on 2020-01-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0015_auto_20200104_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='assesment',
            new_name='marks',
        ),
    ]
