# Generated by Django 3.0 on 2020-01-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0016_auto_20200106_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='studentid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='studentid',
            field=models.IntegerField(),
        ),
    ]
