# Generated by Django 3.0 on 2020-01-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0017_auto_20200106_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyattendance',
            name='id',
        ),
        migrations.AddField(
            model_name='marks',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='facultyattendance',
            name='facultyid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
