# Generated by Django 3.0 on 2020-01-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0018_auto_20200107_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyattendance',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
