# Generated by Django 3.0 on 2020-01-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0020_auto_20200107_1157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studentattendance',
            new_name='sattendance',
        ),
    ]
