# Generated by Django 3.0 on 2020-01-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0022_auto_20200107_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sattendance',
            name='studentid',
            field=models.IntegerField(),
        ),
    ]
