# Generated by Django 3.0 on 2020-01-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attapp', '0023_auto_20200107_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('batch', models.CharField(blank=True, max_length=10, null=True)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
